### ISSUE TITLE
CUDA Illegal memory access when starting training

### ISSUE THREAD

**Issue by marthinwurer** [ClashLuke/HeavyBall#18]
```
0batch [00:00, ?batch/s]

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[21], line 5
      3 for i in range(runs):
      4     start_time = time.time()
----> 5     result, stats, model = train_run(1e-3)
      6     results.append(result)
      7     print("result:", result)

Cell In[20], line 20, in train_run(lr)
     17 stats = defaultdict(list)
     19 start_time = time.time()
---> 20 train_loop(autoencoder, train_dataloader, optimizer, 10, stats)
     21 result = test_loop(autoencoder, test_dataloader)
     22 return result, stats, autoencoder

Cell In[17], line 24, in train_loop(model, dataloader, optimizer, epochs, stats)
     19             image = data.cuda()
     20 #             print(image.shape)
     21 #             break
     22 
     23     #         loss = train_batch(image, model, optimizer, autoencoder.spectral_loss)
---> 24             loss, losses = train_batch(model, image, image, optimizer, F.mse_loss)
     26             if isinstance(losses, tuple):
     27                 stats['raw_losses'].append(loss)

Cell In[16], line 19, in train_batch(model, inputs, targets, optimizer, loss_func)
     16 loss = F.mse_loss(inputs, outputs)
     17 loss.backward()
---> 19 optimizer.step()
     21 return loss.detach().item(), None

File ~/.pyenv/versions/3.9.6/envs/minerl/lib/python3.9/site-packages/torch/optim/optimizer.py:487, in Optimizer.profile_hook_step.<locals>.wrapper(*args, **kwargs)
    482         else:
    483             raise RuntimeError(
    484                 f"{func} must return None or a tuple of (new_args, new_kwargs), but got {result}."
    485             )
--> 487 out = func(*args, **kwargs)
    488 self._optimizer_step_code()
    490 # call optimizer step post hooks

File ~/.pyenv/versions/3.9.6/envs/minerl/lib/python3.9/site-packages/heavyball/utils.py:601, in StatefulOptimizer.step(self, closure)
    599 for top_group in self.param_groups:
    600     for group in self.get_groups(top_group):
--> 601         self._step(group)
    602         if self.use_ema:
    603             self.ema_update(group)

File ~/.pyenv/versions/3.9.6/envs/minerl/lib/python3.9/site-packages/heavyball/precond_schedule_palm_foreach_soap.py:64, in PrecondSchedulePaLMForeachSOAP._step(self, group)
     62     state["exp_avg_sq"] = torch.zeros_like(g, dtype=torch.float32)
     63     init_preconditioner(g, state, max_precond_dim, precondition_1d)
---> 64     update_preconditioner(g, state, max_precond_dim, precondition_1d, 0, True)
     65     continue  # first step is skipped so that we never use the current gradients in the projection.
     67 # Projecting gradients to the eigenbases of Shampoo's preconditioner
     68 # i.e. projecting to the eigenbases of matrices in state['GG']

File ~/.pyenv/versions/3.9.6/envs/minerl/lib/python3.9/site-packages/heavyball/utils.py:423, in update_preconditioner(grad, state, max_precond_dim, precondition_1d, beta, update_precond)
    421 compute_ggt(grad, state['GG'], max_precond_dim, precondition_1d, beta)
    422 if state['Q'] is None:
--> 423     state['Q'] = get_orthogonal_matrix(state['GG'])
    424 if update_precond:
    425     get_orthogonal_matrix_QR(state['GG'], state['Q'], state['exp_avg_sq'])

File ~/.pyenv/versions/3.9.6/envs/minerl/lib/python3.9/site-packages/heavyball/utils.py:320, in get_orthogonal_matrix(mat)
    318 for modifier in (None, torch.double, 'cpu'):
    319     if modifier is not None:
--> 320         m = m.to(modifier)
    321     try:
    322         Q = torch.linalg.eigh(m + 1e-30 * torch.eye(m.shape[0], device=m.device))[1].to(device=device,
    323                                                                                         dtype=dtype)

RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

This is using:
```
    optimizer = heavyball.PrecondSchedulePaLMForeachSOAP(autoencoder.parameters(), lr=lr)
```

It runs fine with default torch sgd, so I assume it's not a problem with my model.

Let me know if you need more information.

**Comment by ClashLuke** [comment]
Hm, I haven't seen that myself. Is the trace above with `CUDA_LAUNCH_BLOCKING=1`? `.double()` and `.cpu()` shouldn't cause illegal memory accesses

**Comment by marthinwurer** [comment]
I tried it again this morning both with CUDA_LAUNCH_BLOCKING=1 and without, and neither triggered the crash. I think it might have had something to do with the other notebooks I still had open with CUDA contexts and some interaction there. I'll close this for now and reopen if I run into it again.

**Comment by marthinwurer** [comment]
I triggered it again, here's the stack trace where I put `os.environ['CUDA_LAUNCH_BLOCKING'] = "1"` at the start of the jupyter notebook.

```
0batch [00:01, ?batch/s]

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[22], line 5
      3 for i in range(runs):
      4     start_time = time.time()
----> 5     result, stats, model = train_run(1e-3)
      6     results.append(result)
      7     print("result:", result)

Cell In[21], line 21, in train_run(lr)
     18 stats = defaultdict(list)
     20 start_time = time.time()
---> 21 train_loop(autoencoder, train_dataloader, optimizer, 10, stats)
     22 result = test_loop(autoencoder, test_dataloader)
     23 return result, stats, autoencoder

Cell In[18], line 24, in train_loop(model, dataloader, optimizer, epochs, stats)
     19             image = data.cuda()
     20 #             print(image.shape)
     21 #             break
     22 
     23     #         loss = train_batch(image, model, optimizer, autoencoder.spectral_loss)
---> 24             loss, losses = train_batch(model, image, image, optimizer, F.mse_loss)
     26             if isinstance(losses, tuple):
     27                 stats['raw_losses'].append(loss)

Cell In[17], line 22, in train_batch(model, inputs, targets, optimizer, loss_func)
     19 # loss = F.mse_loss(inputs, outputs)
     20 loss.backward()
---> 22 optimizer.step()
     24 # return loss.detach().item(), None
     25 return loss.detach().item(), tuple(l.detach().item() for l in losses)

File ~/.pyenv/versions/3.9.6/envs/minerl/lib/python3.9/site-packages/torch/optim/optimizer.py:487, in Optimizer.profile_hook_step.<locals>.wrapper(*args, **kwargs)
    482         else:
    483             raise RuntimeError(
    484                 f"{func} must return None or a tuple of (new_args, new_kwargs), but got {result}."
    485             )
--> 487 out = func(*args, **kwargs)
    488 self._optimizer_step_code()
    490 # call optimizer step post hooks

File ~/.pyenv/versions/3.9.6/envs/minerl/lib/python3.9/site-packages/heavyball/utils.py:601, in StatefulOptimizer.step(self, closure)
    599 for top_group in self.param_groups:
    600     for group in self.get_groups(top_group):
--> 601         self._step(group)
    602         if self.use_ema:
    603             self.ema_update(group)

File ~/.pyenv/versions/3.9.6/envs/minerl/lib/python3.9/site-packages/heavyball/precond_schedule_palm_foreach_soap.py:64, in PrecondSchedulePaLMForeachSOAP._step(self, group)
     62     state["exp_avg_sq"] = torch.zeros_like(g, dtype=torch.float32)
     63     init_preconditioner(g, state, max_precond_dim, precondition_1d)
---> 64     update_preconditioner(g, state, max_precond_dim, precondition_1d, 0, True)
     65     continue  # first step is skipped so that we never use the current gradients in the projection.
     67 # Projecting gradients to the eigenbases of Shampoo's preconditioner
     68 # i.e. projecting to the eigenbases of matrices in state['GG']

File ~/.pyenv/versions/3.9.6/envs/minerl/lib/python3.9/site-packages/heavyball/utils.py:423, in update_preconditioner(grad, state, max_precond_dim, precondition_1d, beta, update_precond)
    421 compute_ggt(grad, state['GG'], max_precond_dim, precondition_1d, beta)
    422 if state['Q'] is None:
--> 423     state['Q'] = get_orthogonal_matrix(state['GG'])
    424 if update_precond:
    425     get_orthogonal_matrix_QR(state['GG'], state['Q'], state['exp_avg_sq'])

File ~/.pyenv/versions/3.9.6/envs/minerl/lib/python3.9/site-packages/heavyball/utils.py:320, in get_orthogonal_matrix(mat)
    318 for modifier in (None, torch.double, 'cpu'):
    319     if modifier is not None:
--> 320         m = m.to(modifier)
    321     try:
    322         Q = torch.linalg.eigh(m + 1e-30 * torch.eye(m.shape[0], device=m.device))[1].to(device=device,
    323                                                                                         dtype=dtype)

RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by jjoshua2** [comment]
I am getting this as well with heavyball.soap, but not heavyball.muon. Did you ever figure anything out here?

**Comment by jjoshua2** [comment]
It seems reducing batchsize from 1024 to 512 maybe makes it work? But I can train 1024 on vanilla soap, and I understand OOM is a different error.

**Comment by ClashLuke** [comment]
Amazing if you can trigger it on demand - that's a very helpful for debugging! Do you have a script I could reproduce this with? What torch, torch-cuda, cuda and nvidia driver version do you have? Where does the error appear with `CUDA_LAUNCH_BLOCKING=1`?

**Comment by jjoshua2** [comment]
rtx 3090
driver version 576.02
torch                     2.7.0+cu118
cuda 12.9
I set batchsize back to 1024 and used that launch_blocking and it worked fine, and I took it off and it still works, even though its exact same thing that didn't work before, even though I had tried several different optimizer configs before and none worked...

**Comment by jjoshua2** [comment]
I think maybe i had switched back to my vanilla soap by mistake. I think I can get error on demand now with this script https://github.com/jjoshua2/CeresTrain/blob/main/src/CeresTrainPy/train.py:
ray.exceptions.RayTaskError(RuntimeError): ray::ImplicitFunc.train() (pid=574432, ip=172.25.19.195, actor_id=562c3e1f58be334e37a000c601000000, repr=train_tune)
  File "/home/josh/.local/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 330, in train
    raise skipped from exception_cause(skipped)
  File "/home/josh/.local/lib/python3.10/site-packages/ray/air/_internal/util.py", line 107, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/home/josh/.local/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 261, in _trainable_func
    output = fn()
  File "/mnt/c/Users/jjosh/CascadeProjects/cerestrain/CeresTrain/src/CeresTrainPy/train.py", line 882, in train_tune
    final_metrics = train_entrypoint(config_tune, checkpoint_dir=checkpoint_dir)
  File "/mnt/c/Users/jjosh/CascadeProjects/cerestrain/CeresTrain/src/CeresTrainPy/train.py", line 865, in train_entrypoint
    return training_loop(checkpoint_dir=checkpoint_dir)
  File "/mnt/c/Users/jjosh/CascadeProjects/cerestrain/CeresTrain/src/CeresTrainPy/train.py", line 704, in training_loop
    optimizer.step()
  File "/home/josh/.local/lib/python3.10/site-packages/lightning/fabric/wrappers.py", line 87, in step
    output = self._strategy.optimizer_step(
  File "/home/josh/.local/lib/python3.10/site-packages/lightning/fabric/strategies/strategy.py", line 204, in optimizer_step
    return self.precision.optimizer_step(optimizer, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/lightning/fabric/plugins/precision/amp.py", line 88, in optimizer_step
    return super().optimizer_step(optimizer, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/lightning/fabric/plugins/precision/precision.py", line 124, in optimizer_step
    return optimizer.step(**kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 124, in wrapper
    return func.__get__(opt, opt.__class__)(*args, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/torch/optim/optimizer.py", line 485, in wrapper
    out = func(*args, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/utils.py", line 1155, in step
    self._step(group)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 989, in _step
    chain(self.state_, group, g, p, *self.fns)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 886, in chain
    update, skip_update = _inner_chain(state, group, update, grad, param, *fns)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 875, in _inner_chain
    update = fn(state, group, update, grad, param)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 73, in __call__
    return self._call(state, group, update, grad, param, vars, *args, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 106, in _call
    return self.fn(state, group, update, grad, param, *args, *vars, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 61, in __call__
    self._init(st, group, *a, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 187, in _init
    self.init_fn(state, group, update, grad, param, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 459, in _init_soap
    utils.init_preconditioner(grad, state, group["max_precond_dim"], group["precondition_1d"])
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/utils.py", line 776, in init_preconditioner
    state["Q"] = get_orthogonal_matrix(state["GG"])
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/utils.py", line 563, in get_orthogonal_matrix
    m = m.double()
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by ClashLuke** [comment]
Perfect, thank you very much! I'll look into it

**Comment by jjoshua2** [comment]
Do you need any more logs to look into it?

**Comment by ClashLuke** [comment]
Unfortunately, I'm currently focussing on a stable heavyball 2.0.0 release and can't spend too much time on this.

If you have the memory available, could you run the code in fp32? There seem to be some bf16 eigh issues.\
Alternatively, a command or self-contained container so I can reproduce this error on dummy data would go a very long way.

Thank you for your patience.

**Comment by jjoshua2** [comment]
tried switching my fabric to 32-true and the storage_dtype to float32 and still get the same error.
``` optimizer = heavyball.ForeachSOAP(
        optim_groups,
        lr=LR,
        weight_decay=WEIGHT_DECAY,
        mars=True,
        eps=1e-9,
        max_precond_size=4096,
        storage_dtype="float32",
        betas=(config.Opt_Beta1, config.Opt_Beta2),
        shampoo_beta=config.Opt_Beta3,
        use_precond_schedule=True
    )```
I also notice sometimes I get this error instead:
``` File "/mnt/c/Users/jjosh/CascadeProjects/cerestrain/CeresTrain/src/CeresTrainPy/train.py", line 824, in training_loop
    optimizer.step()
  File "/home/josh/.local/lib/python3.10/site-packages/lightning/fabric/wrappers.py", line 87, in step
    output = self._strategy.optimizer_step(
  File "/home/josh/.local/lib/python3.10/site-packages/lightning/fabric/strategies/strategy.py", line 204, in optimizer_step
    return self.precision.optimizer_step(optimizer, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/lightning/fabric/plugins/precision/precision.py", line 124, in optimizer_step
    return optimizer.step(**kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 124, in wrapper
    return func.__get__(opt, opt.__class__)(*args, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/torch/optim/optimizer.py", line 485, in wrapper
    out = func(*args, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/utils.py", line 1155, in step
    self._step(group)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 989, in _step
    chain(self.state_, group, g, p, *self.fns)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 886, in chain
    update, skip_update = _inner_chain(state, group, update, grad, param, *fns)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 875, in _inner_chain
    update = fn(state, group, update, grad, param)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 73, in __call__
    return self._call(state, group, update, grad, param, vars, *args, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 106, in _call
    return self.fn(state, group, update, grad, param, *args, *vars, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 73, in __call__
    return self._call(state, group, update, grad, param, vars, *args, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 194, in _call
    return self.fn(state, group, update, grad, param, *args, *vars, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 199, in __call__
    return self.fn(group, update, grad, param, *args, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/chainable.py", line 600, in scale_by_soap
    precond = fn(
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/utils.py", line 1212, in adam_
    _compilable_adam_(exp_avg, exp_avg_sq, grad, beta1, beta2, step, eps)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/utils.py", line 59, in _fn
    return func(*args, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/utils.py", line 1195, in _compilable_adam_
    exp_avg32 = _lerp(exp_avg, g32, beta1)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/utils.py", line 59, in _fn
    return func(*args, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/utils.py", line 1176, in _lerp
    stochastic_lerp_(ea32, grad, 1 - beta)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/utils.py", line 610, in stochastic_lerp_
    _compilable_stochastic_lerp_(x, y, a)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/utils.py", line 59, in _fn
    return func(*args, **kwargs)
  File "/home/josh/.local/lib/python3.10/site-packages/heavyball/utils.py", line 584, in _compilable_stochastic_lerp_
    copy_stochastic_(x_, x32 * (1 - a) + y32 * a)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!```

**Comment by ClashLuke** [comment]
Excellent, that looks like a sufficiently different bug and may be telling us more about the underlying problem! Thank you for following up on this.

Based on the logs, it seems like the state, the original gradient, or the lerp weight is on the CPU while at least one of the other tensors is on the GPU. The lerp weight is initialized based on the other tensors. So, either state or original gradient is on CPU.

Is the optimizer initialized before the model is moved to GPU? Or is one of the tensors on the CPU while another is on the GPU?

I couldn't find either of these issues in the Ceres code on a cursory glance
